//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Авторизация.
    /// </summary>
    // *** Start programmer edit section *** (Авторизация CustomAttributes)

    // *** End programmer edit section *** (Авторизация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("АвторизацияE", new string[] {
            "Id as \'Id\'",
            "Имя as \'Имя\'",
            "Фамилия as \'Фамилия\'"})]
    [View("АвторизацияL", new string[] {
            "Id as \'Id\'",
            "Имя as \'Имя\'",
            "Фамилия as \'Фамилия\'"})]
    public class Авторизация : ICSSoft.STORMNET.DataObject
    {
        
        private int fId;
        
        private string fИмя;
        
        private string fФамилия;
        
        // *** Start programmer edit section *** (Авторизация CustomMembers)

        // *** End programmer edit section *** (Авторизация CustomMembers)

        
        /// <summary>
        /// Id.
        /// </summary>
        // *** Start programmer edit section *** (Авторизация.Id CustomAttributes)

        // *** End programmer edit section *** (Авторизация.Id CustomAttributes)
        public virtual int Id
        {
            get
            {
                // *** Start programmer edit section *** (Авторизация.Id Get start)

                // *** End programmer edit section *** (Авторизация.Id Get start)
                int result = this.fId;
                // *** Start programmer edit section *** (Авторизация.Id Get end)

                // *** End programmer edit section *** (Авторизация.Id Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Авторизация.Id Set start)

                // *** End programmer edit section *** (Авторизация.Id Set start)
                this.fId = value;
                // *** Start programmer edit section *** (Авторизация.Id Set end)

                // *** End programmer edit section *** (Авторизация.Id Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Авторизация.Имя CustomAttributes)

        // *** End programmer edit section *** (Авторизация.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Авторизация.Имя Get start)

                // *** End programmer edit section *** (Авторизация.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Авторизация.Имя Get end)

                // *** End programmer edit section *** (Авторизация.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Авторизация.Имя Set start)

                // *** End programmer edit section *** (Авторизация.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Авторизация.Имя Set end)

                // *** End programmer edit section *** (Авторизация.Имя Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Авторизация.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Авторизация.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Авторизация.Фамилия Get start)

                // *** End programmer edit section *** (Авторизация.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Авторизация.Фамилия Get end)

                // *** End programmer edit section *** (Авторизация.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Авторизация.Фамилия Set start)

                // *** End programmer edit section *** (Авторизация.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Авторизация.Фамилия Set end)

                // *** End programmer edit section *** (Авторизация.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "АвторизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвторизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвторизацияE", typeof(IIS.Otel2.Авторизация));
                }
            }
            
            /// <summary>
            /// "АвторизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View АвторизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("АвторизацияL", typeof(IIS.Otel2.Авторизация));
                }
            }
        }
    }
}
