//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel2
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Доступа.
    /// </summary>
    // *** Start programmer edit section *** (Доступа CustomAttributes)

    // *** End programmer edit section *** (Доступа CustomAttributes)
    public enum Доступа
    {
        
        // *** Start programmer edit section *** (Доступа.Открыт CustomAttributes)

        // *** End programmer edit section *** (Доступа.Открыт CustomAttributes)
        Открыт,
        
        // *** Start programmer edit section *** (Доступа.Закрыт CustomAttributes)

        // *** End programmer edit section *** (Доступа.Закрыт CustomAttributes)
        Закрыт,
    }
}
