//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Допуск.
    /// </summary>
    // *** Start programmer edit section *** (Допуск CustomAttributes)

    // *** End programmer edit section *** (Допуск CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДопускE", new string[] {
            "Комнаты.Отели as \'Отели\'",
            "Комнаты.Отели.Наименование as \'Наименование\'",
            "Гости.Авторизация as \'Авторизация\'",
            "Гости.Авторизация.Имя as \'Имя\'",
            "Гости.Авторизация.Фамилия as \'Фамилия\'",
            "Комнаты as \'Комнаты\'",
            "Комнаты.КомнатаОтеля as \'КомнатаОтеля\'",
            "Гости as \'Гости\'",
            "Гости.Комната as \'Комната\'",
            "Допуск as \'Допуск\'"}, Hidden=new string[] {
            "Комнаты.Отели.Наименование",
            "Гости.Авторизация.Имя",
            "Гости.Авторизация.Фамилия",
            "Гости.Комната"})]
    [MasterViewDefineAttribute("ДопускE", "Комнаты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ID")]
    [MasterViewDefineAttribute("ДопускE", "Гости", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Комната")]
    [View("ДопускL", new string[] {
            "Комнаты.Отели.Наименование as \'Наименование\'",
            "Гости.Авторизация.Имя as \'Имя\'",
            "Гости.Авторизация.Фамилия as \'Фамилия\'",
            "Комнаты.КомнатаОтеля as \'КомнатаОтеля\'",
            "Гости.Комната as \'Комната\'",
            "Допуск as \'Допуск\'"})]
    public class Допуск : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Otel2.Доступа fДопуск;
        
        private IIS.Otel2.Гости fГости;
        
        private IIS.Otel2.Комнаты fКомнаты;
        
        // *** Start programmer edit section *** (Допуск CustomMembers)

        // *** End programmer edit section *** (Допуск CustomMembers)

        
        /// <summary>
        /// Допуск.
        /// </summary>
        // *** Start programmer edit section *** (Допуск.Допуск CustomAttributes)

        // *** End programmer edit section *** (Допуск.Допуск CustomAttributes)
        public virtual IIS.Otel2.Доступа Допуск
        {
            get
            {
                // *** Start programmer edit section *** (Допуск.Допуск Get start)

                // *** End programmer edit section *** (Допуск.Допуск Get start)
                IIS.Otel2.Доступа result = this.fДопуск;
                // *** Start programmer edit section *** (Допуск.Допуск Get end)

                // *** End programmer edit section *** (Допуск.Допуск Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допуск.Допуск Set start)

                // *** End programmer edit section *** (Допуск.Допуск Set start)
                this.fДопуск = value;
                // *** Start programmer edit section *** (Допуск.Допуск Set end)

                // *** End programmer edit section *** (Допуск.Допуск Set end)
            }
        }
        
        /// <summary>
        /// Допуск.
        /// </summary>
        // *** Start programmer edit section *** (Допуск.Гости CustomAttributes)

        // *** End programmer edit section *** (Допуск.Гости CustomAttributes)
        [PropertyStorage(new string[] {
                "Гости"})]
        [NotNull()]
        public virtual IIS.Otel2.Гости Гости
        {
            get
            {
                // *** Start programmer edit section *** (Допуск.Гости Get start)

                // *** End programmer edit section *** (Допуск.Гости Get start)
                IIS.Otel2.Гости result = this.fГости;
                // *** Start programmer edit section *** (Допуск.Гости Get end)

                // *** End programmer edit section *** (Допуск.Гости Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допуск.Гости Set start)

                // *** End programmer edit section *** (Допуск.Гости Set start)
                this.fГости = value;
                // *** Start programmer edit section *** (Допуск.Гости Set end)

                // *** End programmer edit section *** (Допуск.Гости Set end)
            }
        }
        
        /// <summary>
        /// Допуск.
        /// </summary>
        // *** Start programmer edit section *** (Допуск.Комнаты CustomAttributes)

        // *** End programmer edit section *** (Допуск.Комнаты CustomAttributes)
        [PropertyStorage(new string[] {
                "Комнаты"})]
        [NotNull()]
        public virtual IIS.Otel2.Комнаты Комнаты
        {
            get
            {
                // *** Start programmer edit section *** (Допуск.Комнаты Get start)

                // *** End programmer edit section *** (Допуск.Комнаты Get start)
                IIS.Otel2.Комнаты result = this.fКомнаты;
                // *** Start programmer edit section *** (Допуск.Комнаты Get end)

                // *** End programmer edit section *** (Допуск.Комнаты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Допуск.Комнаты Set start)

                // *** End programmer edit section *** (Допуск.Комнаты Set start)
                this.fКомнаты = value;
                // *** Start programmer edit section *** (Допуск.Комнаты Set end)

                // *** End programmer edit section *** (Допуск.Комнаты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДопускE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопускE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопускE", typeof(IIS.Otel2.Допуск));
                }
            }
            
            /// <summary>
            /// "ДопускL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДопускL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДопускL", typeof(IIS.Otel2.Допуск));
                }
            }
        }
    }
}
