//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Otel2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отели.
    /// </summary>
    // *** Start programmer edit section *** (Отели CustomAttributes)

    // *** End programmer edit section *** (Отели CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтелиE", new string[] {
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    [View("ОтелиL", new string[] {
            "Наименование as \'Наименование\'",
            "Адрес as \'Адрес\'"})]
    public class Отели : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private string fАдрес;
        
        // *** Start programmer edit section *** (Отели CustomMembers)

        // *** End programmer edit section *** (Отели CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Отели.Адрес CustomAttributes)

        // *** End programmer edit section *** (Отели.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Отели.Адрес Get start)

                // *** End programmer edit section *** (Отели.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Отели.Адрес Get end)

                // *** End programmer edit section *** (Отели.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отели.Адрес Set start)

                // *** End programmer edit section *** (Отели.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Отели.Адрес Set end)

                // *** End programmer edit section *** (Отели.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Отели.Наименование CustomAttributes)

        // *** End programmer edit section *** (Отели.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Отели.Наименование Get start)

                // *** End programmer edit section *** (Отели.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Отели.Наименование Get end)

                // *** End programmer edit section *** (Отели.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отели.Наименование Set start)

                // *** End programmer edit section *** (Отели.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Отели.Наименование Set end)

                // *** End programmer edit section *** (Отели.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтелиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтелиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтелиE", typeof(IIS.Otel2.Отели));
                }
            }
            
            /// <summary>
            /// "ОтелиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтелиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтелиL", typeof(IIS.Otel2.Отели));
                }
            }
        }
    }
}
